sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=terradueogctb16/eo-processing-sentinel-3-slstr-composite
    - VERSION=0.1

before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build .binder/Dockerfile 

after_script:
  - docker images

before_deploy:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${VERSION}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${VERSION}"
  on:
    branch: master
