name: env_s3
channels:
  - defaults
  - terradue
  - conda-forge
dependencies:
  - snap
  - ipykernel
  - otb
  - gdal>2.2.2
  - poppler<0.66
  - pystac=0.3.3
  - lxml
  - shapely
  - pyyaml
  - instac
  - imageio